services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: logitrack-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./app:/app/app
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local

networks:
  default:
    name: logitrack-network
